version: "3.8"

services:
  app:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    # image: quanghung97/products_microservice:latest
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    restart: always
